<a href="https://colab.research.google.com/github/AliAnusKhan/neurofive-ml-track/blob/main/Titanic_EDA_N5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

This will copy the file path in the file_path variable

In [ ]:
file_path='/content/drive/MyDrive/dataset/Titanic_test.csv'

Importing pandas liabaries for reading of data

In [ ]:
import pandas as pd
nfive=pd.read_csv(file_path)

Now printing top 5 rows

In [ ]:
nfive.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
print("Dataset Info")
nfive.info()

Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [ ]:
print("Statistical Summary")
nfive.describe()

Statistical Summary

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [ ]:
print("Rows & Coulmns")
nfive.shape

Rows & Coulmns

(418, 11)

In [ ]:
print("Missing Values Column")
nfive.isnull().sum()[nfive.isnull().sum() > 0]

Missing Values Column

Age       86
Fare       1
Cabin    327
dtype: int64

In [ ]:
numerical_columns=nfive.select_dtypes(include=['number']).columns
print(numerical_columns)

Index(['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
categorical_coulmns=nfive.select_dtypes(include=['object','category']).columns
print(categorical_coulmns)

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

This notebook begins by mounting Google Drive and loading the Titanic_test.csv dataset into a pandas DataFrame named nfive. Initial data exploration is performed, including displaying the first few rows, checking data types and non-null counts with info(), and generating descriptive statistics with describe(). It also identifies missing values in 'Age', 'Fare', and 'Cabin' columns, and explicitly lists both numerical and categorical features present in the dataset.